logging:
  level:
    org.springframework: WARN
    com.micropace: INFO

# 文件上传路径
upload:
  path: /home/ramp/uploader/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ramp2?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Ramp*u9$0O
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Ramp2018

server:
  address: 47.104.139.165
  domain: 47.104.139.165

mybatis-plus:
  global-config:
    #mapper文件热部署
    refresh-mapper: false

# 阿里云短信
aliyun-sms:
  access-key: LTAIFWBvPFl9q6IQ
  access-secret: NYXjwt63PcUq3fMswzYi59WjJ5OL95